apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackdo-higgs-data
  namespace: csuf-llm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cephfs
  resources:
    requests:
      storage: 10Gi